 {
  "name": "Docker LAMP Lab",
  "dockerFile": "Dockerfile",
  "forwardPorts": [8080],
  "customizations": {
    "vscode": {
      "extensions": [
        "ms-azuretools.vscode-docker"
      ]
    }
  }
}
